# Generated by Django 4.1.4 on 2023-06-29 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options_alter_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='email',
        ),
    ]
