# Generated by Django 4.2.2 on 2023-07-01 02:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0002_alter_cliente_options'),
        ('clientes', '0003_remove_cliente_email'),
    ]

    operations = [
    ]
