# Generated by Django 4.2.2 on 2023-07-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0004_merge_20230630_2211'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correo', models.EmailField(max_length=254)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.TextField()),
                ('ciudad', models.CharField(max_length=50)),
                ('residencia', models.CharField(max_length=50)),
            ],
        ),
    ]
